spawns:
- - -172.0
  - 23.5
  - -139.0
  - -180.275634765625
  - 51.449825286865234
- - -169.0
  - 23.5
  - -142.0
  - -268.1745910644531
  - 63.449913024902344
- - -168.0
  - 23.5
  - -145.0
  - -270.7240905761719
  - 61.499916076660156
- - -169.0
  - 23.5
  - -148.0
  - -305.6727294921875
  - 47.100032806396484
- - -172.0
  - 23.5
  - -151.0
  - -321.5712585449219
  - 69.15005493164062
- - -175.0
  - 23.5
  - -152.0
  - -358.6203918457031
  - 69.60010528564453
- - -178.0
  - 23.5
  - -151.0
  - -28.171875
  - 46.049983978271484
- - -181.0
  - 23.5
  - -148.0
  - -49.319122314453125
  - 43.950035095214844
- - -182.0
  - 23.5
  - -145.0
  - -93.86834716796875
  - 42.44999694824219
- - -181.0
  - 23.5
  - -142.0
  - -126.86782836914062
  - 45.000003814697266
- - -178.0
  - 23.5
  - -139.0
  - -161.51702880859375
  - 61.05020523071289
- - -175.0
  - 23.5
  - -138.0
  - -181.17364501953125
  - 18.449954986572266
- - -180.0
  - 23.5
  - -140.0
  - -162.12062072753906
  - 77.70014190673828
- - -170.0
  - 23.5
  - -140.0
  - -222.27049255371094
  - 50.700096130371094
- - -170.0
  - 23.5
  - -150.0
  - -320.0708923339844
  - 33.89997482299805
- - -180.0
  - 23.5
  - -150.0
  - -47.370513916015625
  - 31.799903869628906
role:
  PetiteFille: 0
  LoupGarou: 2
  Corbeau: 0
  LoupGarouBlanc: 0
  Voyante: 1
  Assassin: 0
  Dictateur: 1
  LoupGarouNoir: 0
  ChaperonRouge: 0
  Faucheur: 0
  EnfantSauvage: 0
  Cupidon: 1
  Chasseur: 0
  Bouffon: 0
  Detective: 1
  GrandMechantLoup: 0
  Survivant: 0
  Garde: 1
  Villageois: 0
  Ange: 0
  Medium: 1
  ChienLoup: 0
  Pyromane: 0
  Pirate: 1
  Pretre: 1
  Sorciere: 1
